---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: setup-ci
    image: autonomy/build-container:latest
    commands:
      - git fetch --tags
      - install-ci-key
      - setup-buildx-amd64-arm64
    environment:
      SSH_KEY:
        from_secret: ssh_key
    resources:
      requests:
        cpu: 24000
        memory: 48GiB
    volumes:
      - name: docker-socket
        path: /var/run
      - name: ssh
        path: /root/.ssh
      - name: docker
        path: /root/.docker/buildx

  - name: build-pull-request
    depends_on:
      - setup-ci
    image: autonomy/build-container:latest
    pull: always
    commands:
      - make
    when:
      event:
        include:
          - pull_request
    volumes:
      - name: docker-socket
        path: /var/run
      - name: ssh
        path: /root/.ssh
      - name: docker
        path: /root/.docker/buildx

  - name: build-nonfree-pull-request
    depends_on:
      - build-pull-request
    image: autonomy/build-container:latest
    pull: always
    commands:
      - make nonfree
    when:
      event:
        include:
          - pull_request
    volumes:
      - name: docker-socket
        path: /var/run
      - name: ssh
        path: /root/.ssh
      - name: docker
        path: /root/.docker/buildx

  - name: reproducibility-test
    depends_on:
      - setup-ci
    image: autonomy/build-container:latest
    pull: always
    commands:
      - make reproducibility-test
    when:
      target:
        include:
          - integration-reproducibility
      event:
        exclude:
          - pull_request
          - tag
    volumes:
      - name: docker-socket
        path: /var/run
      - name: ssh
        path: /root/.ssh
      - name: docker
        path: /root/.docker/buildx

  - name: reproducibility-test-cron
    depends_on:
      - setup-ci
    image: autonomy/build-container:latest
    pull: always
    commands:
      - make reproducibility-test
    when:
      cron:
        - weekly
      event:
        exclude:
          - pull_request
          - tag
    volumes:
      - name: docker-socket
        path: /var/run
      - name: ssh
        path: /root/.ssh
      - name: docker
        path: /root/.docker/buildx

  - name: build-and-publish
    depends_on:
      - setup-ci
    image: autonomy/build-container:latest
    pull: always
    environment:
      GHCR_USERNAME:
        from_secret: ghcr_username
      GHCR_PASSWORD:
        from_secret: ghcr_token
    commands:
      - docker login ghcr.io --username "$${GHCR_USERNAME}" --password "$${GHCR_PASSWORD}"
      - make PUSH=true
    when:
      event:
        exclude:
          - pull_request
          - promote
          - cron
    volumes:
      - name: docker-socket
        path: /var/run
      - name: ssh
        path: /root/.ssh
      - name: docker
        path: /root/.docker/buildx

trigger:
  branch:
    exclude:
      - renovate/*
      - dependabot/*

volumes:
  - name: docker-socket
    host:
      path: /var/ci-docker
  - name: docker
    temp: {}
  - name: ssh
    temp: {}
---
kind: pipeline
type: kubernetes
name: notify

clone:
  disable: true

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: proj-talos-maintainers
    when:
      status:
        - success
        - failure

trigger:
  branch:
    exclude:
      - renovate/*
      - dependabot/*
  status:
  - success
  - failure

depends_on:
  - default
