---
kind: pipeline
name: default

services:
  - name: docker
    image: docker:19.03.3-rc1-dind
    entrypoint:
      - dockerd
    command:
      - --dns=8.8.8.8
      - --dns=8.8.4.4
      - --mtu=1440
      - --log-level=error
    privileged: true
    volumes:
      - name: docker-socket
        path: /var/run

steps:
  - name: build-pull-request
    image: autonomy/build-container:latest
    pull: always
    environment:
      BINDIR: /usr/local/bin
      BUILDKIT_HOST: ${BUILDKIT_HOST=tcp://buildkitd.ci.svc:1234}
    commands:
      - make
    when:
      event:
        include:
          - pull_request
    volumes:
      - name: docker-socket
        path: /var/run

  - name: build-and-publish
    image: autonomy/build-container:latest
    pull: always
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
      BINDIR: /usr/local/bin
      BUILDKIT_HOST: ${BUILDKIT_HOST=tcp://buildkitd.ci.svc:1234}
    commands:
      - docker login --username "$${DOCKER_USERNAME}" --password "$${DOCKER_PASSWORD}"
      - make PUSH=true
    when:
      event:
        exclude:
          - pull_request
    volumes:
      - name: docker-socket
        path: /var/run

volumes:
  - name: docker-socket
    temp: {}
---
kind: pipeline
name: notify

clone:
  disable: true

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: proj-talos-maintainers
    when:
      status:
        - success
        - failure

trigger:
  status:
    - success
    - failure

depends_on:
  - default
