#define COMPAT___VMALLOC_HAS_2_PARAMS
#define COMPAT_ADD_DISK_RETURNS_INT
/* #undef COMPAT_BEFORE_4_13_KERNEL_READ */
#define COMPAT_BIO_ALLOC_HAS_4_PARAMS
#define COMPAT_BLK_ALLOC_DISK_TAKES_QUEUE_LIMITS
/* #undef COMPAT_BLKDEV_GET_BY_PATH_HAS_HOLDER_OPS */
/* #undef COMPAT_BLKDEV_ISSUE_DISCARD_TAKES_FLAGS */
#define COMPAT_BLKDEV_ISSUE_ZEROOUT_DISCARD
/* #undef COMPAT_BLKDEV_PUT_HAS_HOLDER */
#define COMPAT_BLOCK_DEVICE_OPERATIONS_OPEN_TAKES_GENDISK
#define COMPAT_BLOCK_DEVICE_OPERATIONS_RELEASE_TAKES_SINGLE_ARGUMENT
/* #undef COMPAT_CAN_INCLUDE_VERMAGIC_H */
/* #undef COMPAT_DAX_DIRECT_ACCESS_TAKES_MODE */
/* #undef COMPAT_FS_DAX_GET_BY_BDEV_TAKES_START_OFF */
#define COMPAT_FS_DAX_GET_BY_BDEV_TAKES_START_OFF_AND_HOLDER
#define COMPAT_GENL_POLICY_IN_OPS
#define COMPAT_GENLMSG_MULTICAST_ALLNS_HAS_4_PARAMS
#define COMPAT_HAVE_BIO_MAX_VECS
#define COMPAT_HAVE_GENHD_FL_NO_PART
#define COMPAT_HAVE___BIO_ADD_PAGE
/* #undef COMPAT_HAVE_ALLOC_OBJ_DEFAULT_GFP */
#define COMPAT_HAVE_ALLOW_KERNEL_SIGNAL
#define COMPAT_HAVE_BDEV_DISCARD_GRANULARITY
#define COMPAT_HAVE_BDEV_FILE_OPEN_BY_PATH
#define COMPAT_HAVE_BDEV_FREEZE
#define COMPAT_HAVE_BDEV_MAX_DISCARD_SECTORS
#define COMPAT_HAVE_BDEV_NR_SECTORS
/* #undef COMPAT_HAVE_BDEV_OPEN_BY_PATH */
/* #undef COMPAT_HAVE_BDEVNAME */
/* #undef COMPAT_HAVE_BDGRAB */
/* #undef COMPAT_HAVE_BDI_CONGESTED */
/* #undef COMPAT_HAVE_BDI_CONGESTED_FN */
#define COMPAT_HAVE_BIO_ADVANCE_ITER_SINGLE
#define COMPAT_HAVE_BIO_ALLOC_CLONE
#define COMPAT_HAVE_BIO_BI_BDEV
#define COMPAT_HAVE_BIO_FOR_EACH_BVEC
#define COMPAT_HAVE_BIO_MAX_SEGS
#define COMPAT_HAVE_BIO_SPLIT_TO_LIMITS
#define COMPAT_HAVE_BIO_START_IO_ACCT
#define COMPAT_HAVE_BIOSET_INIT
/* #undef COMPAT_HAVE_BLK_ALLOC_DISK */
/* #undef COMPAT_HAVE_BLK_ALLOC_QUEUE_RH */
/* #undef COMPAT_HAVE_BLK_CLEANUP_DISK */
#define COMPAT_HAVE_BLK_FEAT_STABLE_WRITES
#define COMPAT_HAVE_BLK_MODE_T
#define COMPAT_HAVE_BLK_OPF_T
#define COMPAT_HAVE_BLK_QC_T_SUBMIT_BIO
#define COMPAT_HAVE_BLK_QUEUE_FLAG_SET
/* #undef COMPAT_HAVE_BLK_QUEUE_MAKE_REQUEST */
/* #undef COMPAT_HAVE_BLK_QUEUE_MAX_WRITE_SAME_SECTORS */
/* #undef COMPAT_HAVE_BLK_QUEUE_SPLIT_BIO */
/* #undef COMPAT_HAVE_BLK_QUEUE_SPLIT_Q_BIO */
/* #undef COMPAT_HAVE_BLK_QUEUE_UPDATE_READAHEAD */
#define COMPAT_HAVE_BVEC_KMAP_LOCAL
/* #undef COMPAT_HAVE_BVEC_NTH_PAGE */
#define COMPAT_HAVE_BVEC_VIRT
#define COMPAT_HAVE_COUNTED_BY
#define COMPAT_HAVE_DEBUGFS_CHANGE_NAME
/* #undef COMPAT_HAVE_DISK_UPDATE_READAHEAD */
#define COMPAT_HAVE_ENUM_REQ_OP
#define COMPAT_HAVE_FALLTHROUGH
#define COMPAT_HAVE_FS_DAX_GET_BY_BDEV
#define COMPAT_HAVE_GENL_INFO_USERHDR
#define COMPAT_HAVE_GENL_PRE_DOIT_SPLIT_OPS
#define COMPAT_HAVE_GET_RANDOM_U32
#define COMPAT_HAVE_GET_RANDOM_U32_BELOW
/* #undef COMPAT_HAVE_HD_STRUCT */
#define COMPAT_HAVE_IB_ALLOC_CQ_ANY
#define COMPAT_HAVE_ITER_SOURCE
#define COMPAT_HAVE_KMALLOC_OBJ
/* #undef COMPAT_HAVE_KMAP_LOCAL_PAGE */
/* #undef COMPAT_HAVE_KVFREE_RCU */
#define COMPAT_HAVE_KVFREE_RCU_MIGHTSLEEP
/* #undef COMPAT_HAVE_KZALLOC_FLEX */
#define COMPAT_HAVE_LINUX_UNALIGNED_H
#define COMPAT_HAVE_LIST_IS_FIRST
#define COMPAT_HAVE_LOOKUP_USER_KEY
#define COMPAT_HAVE_MAX_SEND_RECV_SGE
#define COMPAT_HAVE_MEMPOOL_IS_SATURATED
#define COMPAT_HAVE_NLA_NEST_START_NOFLAG
#define COMPAT_HAVE_NLA_PARSE_DEPRECATED
#define COMPAT_HAVE_NLA_STRSCPY
#define COMPAT_HAVE_PART_STAT_H
#define COMPAT_HAVE_PART_STAT_READ_ACCUM
/* #undef COMPAT_HAVE_PFN_T */
#define COMPAT_HAVE_PROC_CREATE_SINGLE
/* #undef COMPAT_HAVE_QUEUE_FLAG_DISCARD */
/* #undef COMPAT_HAVE_QUEUE_FLAG_STABLE_WRITES */
#define COMPAT_HAVE_QUEUE_LIMITS_START_UPDATE
#define COMPAT_HAVE_RB_DECLARE_CALLBACKS_MAX
/* #undef COMPAT_HAVE_REVALIDATE_DISK_SIZE */
#define COMPAT_HAVE_SANE_TEST_ENVIRONMENT
/* #undef COMPAT_HAVE_SANE_TEST_ENVIRONMENT_ALWAYS_FAIL */
#define COMPAT_HAVE_SCHED_SET_FIFO
/* #undef COMPAT_HAVE_SENDPAGE */
#define COMPAT_HAVE_SENDPAGE_OK
#define COMPAT_HAVE_SET_CAPACITY_AND_NOTIFY
#define COMPAT_HAVE_SK_USE_TASK_FRAG
#define COMPAT_HAVE_SOCK_SET_KEEPALIVE
#define COMPAT_HAVE_STRUCT_SIZE
/* #undef COMPAT_HAVE_STRUCT_SOCKADDR_UNSIZED */
#define COMPAT_HAVE_SUBMIT_BIO_NOACCT
#define COMPAT_HAVE_TASKLET_SETUP
#define COMPAT_HAVE_TCP_SOCK_SET_CORK
#define COMPAT_HAVE_TCP_SOCK_SET_KEEPCNT
#define COMPAT_HAVE_TCP_SOCK_SET_KEEPIDLE
#define COMPAT_HAVE_TCP_SOCK_SET_NODELAY
#define COMPAT_HAVE_TCP_SOCK_SET_QUICKACK
#define COMPAT_HAVE_TIMER_CONTAINER_OF
#define COMPAT_HAVE_TIMER_DELETE
#define COMPAT_HAVE_TIMER_SHUTDOWN
#define COMPAT_HAVE_TLS_GET_RECORD_TYPE
#define COMPAT_HAVE_TLS_TX_RX
#define COMPAT_HAVE_VOID_SUBMIT_BIO
#define COMPAT_IB_DEVICE_HAS_OPS
#define COMPAT_IB_POST_SEND_CONST_PARAMS
/* #undef COMPAT_NEED_DRBD_WRAPPERS */
/* #undef COMPAT_NEED_RECALC_SIGPENDING */
#define COMPAT_PART_STAT_READ_TAKES_BLOCK_DEVICE
#define COMPAT_QUEUE_LIMITS_HAS_FEATURES
#define COMPAT_QUEUE_LIMITS_HAS_MAX_HW_DISCARD_SECTORS
#define COMPAT_QUEUE_LIMITS_HAS_MAX_HW_WZEROES_UNMAP_SECTORS
#define COMPAT_QUEUE_LIMITS_HAS_MAX_HW_ZONE_APPEND_SECTORS
#define COMPAT_QUEUE_LIMITS_HAS_MAX_ZONE_APPEND_SECTORS
#define COMPAT_RDMA_REJECT_HAS_REASON_ARG
#define COMPAT_SOCK_OPS_RETURNS_ADDR_LEN
#define COMPAT_STRUCT_GENDISK_HAS_BACKING_DEV_INFO
/* #undef COMPAT_THAW_BDEV_TAKES_SUPER_BLOCK */
