#! /bin/bash
set -euo pipefail

# export GCP_CLOUD_AUDIENCE;GCP_CLOUD_AUDIENCE="$(buildkite-agent secret get GCP_CLOUD_AUDIENCE)"
# export GCP_CLOUD_SERVICE_ACCOUNT;GCP_CLOUD_SERVICE_ACCOUNT="$(buildkite-agent secret get GCP_CLOUD_SERVICE_ACCOUNT)"
# export IMAGE_ARTIFACT_REGISTRY_REPO="us-docker.pkg.dev/prj-c-cloud-cicd-8fbb/"
# export MANIFEST_ARTIFACT_REGISTRY_REPO="us-docker.pkg.dev/prj-c-cloud-cicd-8fbb/groq-deploy-manifests"

# needed to pull groq's hermit-packages
export HERMIT_GITHUB_TOKEN;HERMIT_GITHUB_TOKEN="$(groqkite gh token)"